version: "3.8"

services:
  db:
    image: mysql:8  # ✅ Use the official MySQL 8 image instead of building one
    container_name: mysql_db
    restart: always
    environment:
      TZ: Asia/Jerusalem
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: growhire
      MYSQL_USER: growhire_user
      MYSQL_PASSWORD: growhire_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # ✅ Persistent database storage
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # ✅ Ensure correct path and read-only
      - ../db/my.cnf:/etc/mysql/my.cnf:ro  # ✅ Mount custom config instead of copying
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - growhire_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"  # ✅ Access phpMyAdmin via http://localhost:8080
    networks:
      - growhire_network

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: growhire_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app
    environment:
      DATABASE_URL: mysql+pymysql://root:root@db:3306/growhire
      DISPLAY: ":99"
      QT_X11_NO_MITSHM: "1"
    ports:
      - "5000:5000"
      - "4444:4444"
      - "5900:5900"
      - "9222:9222"
      - "6080:6080"
    volumes:
      - ../resume:/app/resume
      - ../app/utils:/app/utils
    networks:
      - growhire_network
    command: >
      /bin/bash -c "Xvfb :99 -screen 0 1920x1080x24 & sleep 2 && setxkbmap us && mkdir -p ~/.fluxbox && echo 'session.screen0.toolbar.visible: false' > ~/.fluxbox/init && fluxbox & x11vnc -forever -display :99 -rfbport 5900 -bg && nohup websockify --web /usr/share/novnc/ 6080 localhost:5900 > /var/log/websockify.log 2>&1 & /app/venv/bin/python3 main.py"

volumes:
  mysql_data:

networks:
  growhire_network:
